name: Cancel Jobs on Merge

on:
  pull_request:
    types: [closed]

permissions:
  actions: write

jobs:
  cancel:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel running workflows for PR
        uses: actions/github-script@v7
        with:
          script: |
            const branch = '${{ github.event.pull_request.head.ref }}';
            const runs = await github.paginate(
              github.rest.actions.listWorkflowRunsForRepo,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch,
                status: 'in_progress'
              }
            );
            for (const run of runs) {
              await github.rest.actions.cancelWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id
              });
            }

