name: Delete merged branches

on:
  pull_request:
    types: [closed]

jobs:
  delete:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: peter-evans/delete-branch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
